class ImportInitialLocations < ActiveRecord::Migration[5.0]
  def up
    # Data is taken from https://country.register.gov.uk/records
    Location.create!(code: "AF", name: "Afghanistan", start_date: nil, end_date: nil)
    Location.create!(code: "AL", name: "Albania", start_date: nil, end_date: nil)
    Location.create!(code: "DZ", name: "Algeria", start_date: nil, end_date: nil)
    Location.create!(code: "AD", name: "Andorra", start_date: nil, end_date: nil)
    Location.create!(code: "AO", name: "Angola", start_date: "1975-11-11", end_date: nil)
    Location.create!(code: "AG", name: "Antigua and Barbuda", start_date: "1981-11-01", end_date: nil)
    Location.create!(code: "AR", name: "Argentina", start_date: nil, end_date: nil)
    Location.create!(code: "AM", name: "Armenia", start_date: "1991-09-21", end_date: nil)
    Location.create!(code: "AU", name: "Australia", start_date: nil, end_date: nil)
    Location.create!(code: "AT", name: "Austria", start_date: nil, end_date: nil)
    Location.create!(code: "AZ", name: "Azerbaijan", start_date: "1991-08-30", end_date: nil)
    Location.create!(code: "BH", name: "Bahrain", start_date: nil, end_date: nil)
    Location.create!(code: "BD", name: "Bangladesh", start_date: nil, end_date: nil)
    Location.create!(code: "BB", name: "Barbados", start_date: nil, end_date: nil)
    Location.create!(code: "BY", name: "Belarus", start_date: "1991-08-25", end_date: nil)
    Location.create!(code: "BE", name: "Belgium", start_date: nil, end_date: nil)
    Location.create!(code: "BZ", name: "Belize", start_date: "1981-09-21", end_date: nil)
    Location.create!(code: "BJ", name: "Benin", start_date: nil, end_date: nil)
    Location.create!(code: "BT", name: "Bhutan", start_date: nil, end_date: nil)
    Location.create!(code: "BO", name: "Bolivia", start_date: nil, end_date: nil)
    Location.create!(code: "BA", name: "Bosnia and Herzegovina", start_date: "1992-03-03", end_date: nil)
    Location.create!(code: "BW", name: "Botswana", start_date: nil, end_date: nil)
    Location.create!(code: "BR", name: "Brazil", start_date: nil, end_date: nil)
    Location.create!(code: "BN", name: "Brunei", start_date: "1984-01-01", end_date: nil)
    Location.create!(code: "BG", name: "Bulgaria", start_date: nil, end_date: nil)
    Location.create!(code: "BF", name: "Burkina Faso", start_date: nil, end_date: nil)
    Location.create!(code: "MM", name: "Burma", start_date: nil, end_date: nil)
    Location.create!(code: "BI", name: "Burundi", start_date: nil, end_date: nil)
    Location.create!(code: "KH", name: "Cambodia", start_date: nil, end_date: nil)
    Location.create!(code: "CM", name: "Cameroon", start_date: nil, end_date: nil)
    Location.create!(code: "CA", name: "Canada", start_date: nil, end_date: nil)
    Location.create!(code: "CV", name: "Cape Verde", start_date: "1975-07-05", end_date: nil)
    Location.create!(code: "CF", name: "Central African Republic", start_date: nil, end_date: nil)
    Location.create!(code: "TD", name: "Chad", start_date: nil, end_date: nil)
    Location.create!(code: "CL", name: "Chile", start_date: nil, end_date: nil)
    Location.create!(code: "CN", name: "China", start_date: nil, end_date: nil)
    Location.create!(code: "CO", name: "Colombia", start_date: nil, end_date: nil)
    Location.create!(code: "KM", name: "Comoros", start_date: "1975-07-06", end_date: nil)
    Location.create!(code: "CG", name: "Congo", start_date: nil, end_date: nil)
    Location.create!(code: "CD", name: "Congo (Democratic Republic)", start_date: nil, end_date: nil)
    Location.create!(code: "CR", name: "Costa Rica", start_date: nil, end_date: nil)
    Location.create!(code: "HR", name: "Croatia", start_date: "1991-06-25", end_date: nil)
    Location.create!(code: "CU", name: "Cuba", start_date: nil, end_date: nil)
    Location.create!(code: "CY", name: "Cyprus", start_date: nil, end_date: nil)
    Location.create!(code: "CZ", name: "Czechia", start_date: "1993-01-01", end_date: nil)
    Location.create!(code: "CS", name: "Czechoslovakia", start_date: "", end_date: "1992-12-31")
    Location.create!(code: "DK", name: "Denmark", start_date: nil, end_date: nil)
    Location.create!(code: "DJ", name: "Djibouti", start_date: "1977-06-27", end_date: nil)
    Location.create!(code: "DM", name: "Dominica", start_date: "1978-11-03", end_date: nil)
    Location.create!(code: "DO", name: "Dominican Republic", start_date: nil, end_date: nil)
    Location.create!(code: "DD", name: "East Germany", start_date: "", end_date: "1990-10-02")
    Location.create!(code: "TL", name: "East Timor", start_date: nil, end_date: nil)
    Location.create!(code: "EC", name: "Ecuador", start_date: nil, end_date: nil)
    Location.create!(code: "EG", name: "Egypt", start_date: nil, end_date: nil)
    Location.create!(code: "SV", name: "El Salvador", start_date: nil, end_date: nil)
    Location.create!(code: "GQ", name: "Equatorial Guinea", start_date: nil, end_date: nil)
    Location.create!(code: "ER", name: "Eritrea", start_date: "1993-05-24", end_date: nil)
    Location.create!(code: "EE", name: "Estonia", start_date: "1991-08-20", end_date: nil)
    Location.create!(code: "ET", name: "Ethiopia", start_date: nil, end_date: nil)
    Location.create!(code: "FJ", name: "Fiji", start_date: nil, end_date: nil)
    Location.create!(code: "FI", name: "Finland", start_date: nil, end_date: nil)
    Location.create!(code: "FR", name: "France", start_date: nil, end_date: nil)
    Location.create!(code: "GA", name: "Gabon", start_date: nil, end_date: nil)
    Location.create!(code: "GE", name: "Georgia", start_date: "1991-04-09", end_date: nil)
    Location.create!(code: "DE", name: "Germany", start_date: "1990-10-03", end_date: nil)
    Location.create!(code: "GH", name: "Ghana", start_date: nil, end_date: nil)
    Location.create!(code: "GR", name: "Greece", start_date: nil, end_date: nil)
    Location.create!(code: "GD", name: "Grenada", start_date: "1974-02-07", end_date: nil)
    Location.create!(code: "GT", name: "Guatemala", start_date: nil, end_date: nil)
    Location.create!(code: "GN", name: "Guinea", start_date: nil, end_date: nil)
    Location.create!(code: "GW", name: "Guinea-Bissau", start_date: nil, end_date: nil)
    Location.create!(code: "GY", name: "Guyana", start_date: nil, end_date: nil)
    Location.create!(code: "HT", name: "Haiti", start_date: nil, end_date: nil)
    Location.create!(code: "HN", name: "Honduras", start_date: nil, end_date: nil)
    Location.create!(code: "HU", name: "Hungary", start_date: nil, end_date: nil)
    Location.create!(code: "IS", name: "Iceland", start_date: nil, end_date: nil)
    Location.create!(code: "IN", name: "India", start_date: nil, end_date: nil)
    Location.create!(code: "ID", name: "Indonesia", start_date: nil, end_date: nil)
    Location.create!(code: "IR", name: "Iran", start_date: nil, end_date: nil)
    Location.create!(code: "IQ", name: "Iraq", start_date: nil, end_date: nil)
    Location.create!(code: "IE", name: "Ireland", start_date: nil, end_date: nil)
    Location.create!(code: "IL", name: "Israel", start_date: nil, end_date: nil)
    Location.create!(code: "IT", name: "Italy", start_date: nil, end_date: nil)
    Location.create!(code: "CI", name: "Ivory Coast", start_date: nil, end_date: nil)
    Location.create!(code: "JM", name: "Jamaica", start_date: nil, end_date: nil)
    Location.create!(code: "JP", name: "Japan", start_date: nil, end_date: nil)
    Location.create!(code: "JO", name: "Jordan", start_date: nil, end_date: nil)
    Location.create!(code: "KZ", name: "Kazakhstan", start_date: "1991-12-16", end_date: nil)
    Location.create!(code: "KE", name: "Kenya", start_date: nil, end_date: nil)
    Location.create!(code: "KI", name: "Kiribati", start_date: "1979-07-12", end_date: nil)
    Location.create!(code: "XK", name: "Kosovo", start_date: nil, end_date: nil)
    Location.create!(code: "KW", name: "Kuwait", start_date: nil, end_date: nil)
    Location.create!(code: "KG", name: "Kyrgyzstan", start_date: "1991-08-31", end_date: nil)
    Location.create!(code: "LA", name: "Laos", start_date: nil, end_date: nil)
    Location.create!(code: "LV", name: "Latvia", start_date: "1990-05-04", end_date: nil)
    Location.create!(code: "LB", name: "Lebanon", start_date: nil, end_date: nil)
    Location.create!(code: "LS", name: "Lesotho", start_date: nil, end_date: nil)
    Location.create!(code: "LR", name: "Liberia", start_date: nil, end_date: nil)
    Location.create!(code: "LY", name: "Libya", start_date: nil, end_date: nil)
    Location.create!(code: "LI", name: "Liechtenstein", start_date: nil, end_date: nil)
    Location.create!(code: "LT", name: "Lithuania", start_date: "1990-03-11", end_date: nil)
    Location.create!(code: "LU", name: "Luxembourg", start_date: nil, end_date: nil)
    Location.create!(code: "MK", name: "Macedonia", start_date: "1991-09-08", end_date: nil)
    Location.create!(code: "MG", name: "Madagascar", start_date: nil, end_date: nil)
    Location.create!(code: "MW", name: "Malawi", start_date: nil, end_date: nil)
    Location.create!(code: "MY", name: "Malaysia", start_date: nil, end_date: nil)
    Location.create!(code: "MV", name: "Maldives", start_date: nil, end_date: nil)
    Location.create!(code: "ML", name: "Mali", start_date: nil, end_date: nil)
    Location.create!(code: "MT", name: "Malta", start_date: nil, end_date: nil)
    Location.create!(code: "MH", name: "Marshall Islands", start_date: "1986-10-21", end_date: nil)
    Location.create!(code: "MR", name: "Mauritania", start_date: nil, end_date: nil)
    Location.create!(code: "MU", name: "Mauritius", start_date: nil, end_date: nil)
    Location.create!(code: "MX", name: "Mexico", start_date: nil, end_date: nil)
    Location.create!(code: "FM", name: "Micronesia", start_date: "1986-11-03", end_date: nil)
    Location.create!(code: "MD", name: "Moldova", start_date: "1991-08-27", end_date: nil)
    Location.create!(code: "MC", name: "Monaco", start_date: nil, end_date: nil)
    Location.create!(code: "MN", name: "Mongolia", start_date: nil, end_date: nil)
    Location.create!(code: "ME", name: "Montenegro", start_date: nil, end_date: nil)
    Location.create!(code: "MA", name: "Morocco", start_date: nil, end_date: nil)
    Location.create!(code: "MZ", name: "Mozambique", start_date: "1975-06-25", end_date: nil)
    Location.create!(code: "NA", name: "Namibia", start_date: "1980-03-21", end_date: nil)
    Location.create!(code: "NR", name: "Nauru", start_date: nil, end_date: nil)
    Location.create!(code: "NP", name: "Nepal", start_date: nil, end_date: nil)
    Location.create!(code: "NL", name: "Netherlands", start_date: nil, end_date: nil)
    Location.create!(code: "NZ", name: "New Zealand", start_date: nil, end_date: nil)
    Location.create!(code: "NI", name: "Nicaragua", start_date: nil, end_date: nil)
    Location.create!(code: "NE", name: "Niger", start_date: nil, end_date: nil)
    Location.create!(code: "NG", name: "Nigeria", start_date: nil, end_date: nil)
    Location.create!(code: "KP", name: "North Korea", start_date: nil, end_date: nil)
    Location.create!(code: "NO", name: "Norway", start_date: nil, end_date: nil)
    Location.create!(code: "OM", name: "Oman", start_date: nil, end_date: nil)
    Location.create!(code: "PK", name: "Pakistan", start_date: nil, end_date: nil)
    Location.create!(code: "PW", name: "Palau", start_date: "1994-10-01", end_date: nil)
    Location.create!(code: "PA", name: "Panama", start_date: nil, end_date: nil)
    Location.create!(code: "PG", name: "Papua New Guinea", start_date: "1975-09-16", end_date: nil)
    Location.create!(code: "PY", name: "Paraguay", start_date: nil, end_date: nil)
    Location.create!(code: "PE", name: "Peru", start_date: nil, end_date: nil)
    Location.create!(code: "PH", name: "Philippines", start_date: nil, end_date: nil)
    Location.create!(code: "PL", name: "Poland", start_date: nil, end_date: nil)
    Location.create!(code: "PT", name: "Portugal", start_date: nil, end_date: nil)
    Location.create!(code: "QA", name: "Qatar", start_date: nil, end_date: nil)
    Location.create!(code: "RO", name: "Romania", start_date: nil, end_date: nil)
    Location.create!(code: "RU", name: "Russia", start_date: "1991-12-25", end_date: nil)
    Location.create!(code: "RW", name: "Rwanda", start_date: nil, end_date: nil)
    Location.create!(code: "WS", name: "Samoa", start_date: nil, end_date: nil)
    Location.create!(code: "SM", name: "San Marino", start_date: nil, end_date: nil)
    Location.create!(code: "ST", name: "Sao Tome and Principe", start_date: "1975-07-12", end_date: nil)
    Location.create!(code: "SA", name: "Saudi Arabia", start_date: nil, end_date: nil)
    Location.create!(code: "SN", name: "Senegal", start_date: nil, end_date: nil)
    Location.create!(code: "RS", name: "Serbia", start_date: nil, end_date: nil)
    Location.create!(code: "SC", name: "Seychelles", start_date: "1976-06-29", end_date: nil)
    Location.create!(code: "SL", name: "Sierra Leone", start_date: nil, end_date: nil)
    Location.create!(code: "SG", name: "Singapore", start_date: nil, end_date: nil)
    Location.create!(code: "SK", name: "Slovakia", start_date: "1993-01-01", end_date: nil)
    Location.create!(code: "SI", name: "Slovenia", start_date: "1991-06-25", end_date: nil)
    Location.create!(code: "SB", name: "Solomon Islands", start_date: "1978-07-07", end_date: nil)
    Location.create!(code: "SO", name: "Somalia", start_date: nil, end_date: nil)
    Location.create!(code: "ZA", name: "South Africa", start_date: nil, end_date: nil)
    Location.create!(code: "KR", name: "South Korea", start_date: nil, end_date: nil)
    Location.create!(code: "SS", name: "South Sudan", start_date: "2011-07-09", end_date: nil)
    Location.create!(code: "ES", name: "Spain", start_date: nil, end_date: nil)
    Location.create!(code: "LK", name: "Sri Lanka", start_date: nil, end_date: nil)
    Location.create!(code: "KN", name: "St Kitts and Nevis", start_date: "1983-09-19", end_date: nil)
    Location.create!(code: "LC", name: "St Lucia", start_date: "1979-02-22", end_date: nil)
    Location.create!(code: "VC", name: "St Vincent", start_date: "1979-10-27", end_date: nil)
    Location.create!(code: "SD", name: "Sudan", start_date: nil, end_date: nil)
    Location.create!(code: "SR", name: "Suriname", start_date: "1975-11-25", end_date: nil)
    Location.create!(code: "SZ", name: "Swaziland", start_date: nil, end_date: nil)
    Location.create!(code: "SE", name: "Sweden", start_date: nil, end_date: nil)
    Location.create!(code: "CH", name: "Switzerland", start_date: nil, end_date: nil)
    Location.create!(code: "SY", name: "Syria", start_date: nil, end_date: nil)
    Location.create!(code: "TJ", name: "Tajikistan", start_date: "1991-09-09", end_date: nil)
    Location.create!(code: "TZ", name: "Tanzania", start_date: nil, end_date: nil)
    Location.create!(code: "TH", name: "Thailand", start_date: nil, end_date: nil)
    Location.create!(code: "BS", name: "The Bahamas", start_date: nil, end_date: nil)
    Location.create!(code: "GM", name: "The Gambia", start_date: nil, end_date: nil)
    Location.create!(code: "TG", name: "Togo", start_date: nil, end_date: nil)
    Location.create!(code: "TO", name: "Tonga", start_date: nil, end_date: nil)
    Location.create!(code: "TT", name: "Trinidad and Tobago", start_date: nil, end_date: nil)
    Location.create!(code: "TN", name: "Tunisia", start_date: nil, end_date: nil)
    Location.create!(code: "TR", name: "Turkey", start_date: nil, end_date: nil)
    Location.create!(code: "TM", name: "Turkmenistan", start_date: "1991-10-27", end_date: nil)
    Location.create!(code: "TV", name: "Tuvalu", start_date: "1978-10-01", end_date: nil)
    Location.create!(code: "SU", name: "USSR", start_date: "", end_date: "1991-12-25")
    Location.create!(code: "UG", name: "Uganda", start_date: nil, end_date: nil)
    Location.create!(code: "UA", name: "Ukraine", start_date: "1991-08-24", end_date: nil)
    Location.create!(code: "AE", name: "United Arab Emirates", start_date: nil, end_date: nil)
    Location.create!(code: "GB", name: "United Kingdom", start_date: nil, end_date: nil)
    Location.create!(code: "US", name: "United States", start_date: nil, end_date: nil)
    Location.create!(code: "UY", name: "Uruguay", start_date: nil, end_date: nil)
    Location.create!(code: "UZ", name: "Uzbekistan", start_date: "1991-09-01", end_date: nil)
    Location.create!(code: "VU", name: "Vanuatu", start_date: "1980-07-30", end_date: nil)
    Location.create!(code: "VA", name: "Vatican City", start_date: nil, end_date: nil)
    Location.create!(code: "VE", name: "Venezuela", start_date: nil, end_date: nil)
    Location.create!(code: "VN", name: "Vietnam", start_date: nil, end_date: nil)
    Location.create!(code: "YE", name: "Yemen", start_date: "1990-05-22", end_date: nil)
    Location.create!(code: "YU", name: "Yugoslavia", start_date: "", end_date: "1992-04-28")
    Location.create!(code: "ZM", name: "Zambia", start_date: nil, end_date: nil)
    Location.create!(code: "ZW", name: "Zimbabwe", start_date: "1980-04-18", end_date: nil)

    # Data is taken from https://territory.register.gov.uk/records
    Location.create!(code: "AE-AZ", name: "Abu Dhabi", start_date: nil, end_date: nil)
    Location.create!(code: "AE-AJ", name: "Ajman", start_date: nil, end_date: nil)
    Location.create!(code: "XQZ", name: "Akrotiri", start_date: nil, end_date: nil)
    Location.create!(code: "AS", name: "American Samoa", start_date: nil, end_date: nil)
    Location.create!(code: "AI", name: "Anguilla", start_date: nil, end_date: nil)
    Location.create!(code: "AQ", name: "Antarctica", start_date: nil, end_date: nil)
    Location.create!(code: "AW", name: "Aruba", start_date: nil, end_date: nil)
    Location.create!(code: "SH-AC", name: "Ascension", start_date: nil, end_date: nil)
    Location.create!(code: "UM-81", name: "Baker Island", start_date: nil, end_date: nil)
    Location.create!(code: "BM", name: "Bermuda", start_date: nil, end_date: nil)
    Location.create!(code: "BQ-BO", name: "Bonaire", start_date: nil, end_date: nil)
    Location.create!(code: "BV", name: "Bouvet Island", start_date: nil, end_date: nil)
    Location.create!(code: "BAT", name: "British Antarctic Territory", start_date: nil, end_date: nil)
    Location.create!(code: "IO", name: "British Indian Ocean Territory", start_date: nil, end_date: nil)
    Location.create!(code: "VG", name: "British Virgin Islands", start_date: nil, end_date: nil)
    Location.create!(code: "KY", name: "Cayman Islands", start_date: nil, end_date: nil)
    Location.create!(code: "ES-CE", name: "Ceuta", start_date: nil, end_date: nil)
    Location.create!(code: "CX", name: "Christmas Island", start_date: nil, end_date: nil)
    Location.create!(code: "CC", name: "Cocos (Keeling) Islands", start_date: nil, end_date: nil)
    Location.create!(code: "CK", name: "Cook Islands", start_date: nil, end_date: nil)
    Location.create!(code: "CW", name: "Curaçao", start_date: nil, end_date: nil)
    Location.create!(code: "XXD", name: "Dhekelia", start_date: nil, end_date: nil)
    Location.create!(code: "AE-DU", name: "Dubai", start_date: nil, end_date: nil)
    Location.create!(code: "FK", name: "Falkland Islands", start_date: nil, end_date: nil)
    Location.create!(code: "FO", name: "Faroe Islands", start_date: nil, end_date: nil)
    Location.create!(code: "GF", name: "French Guiana", start_date: nil, end_date: nil)
    Location.create!(code: "PF", name: "French Polynesia", start_date: nil, end_date: nil)
    Location.create!(code: "TF", name: "French Southern Territories", start_date: nil, end_date: nil)
    Location.create!(code: "AE-FU", name: "Fujairah", start_date: nil, end_date: nil)
    Location.create!(code: "GI", name: "Gibraltar", start_date: nil, end_date: nil)
    Location.create!(code: "GL", name: "Greenland", start_date: nil, end_date: nil)
    Location.create!(code: "GP", name: "Guadeloupe", start_date: nil, end_date: nil)
    Location.create!(code: "GU", name: "Guam", start_date: nil, end_date: nil)
    Location.create!(code: "GG", name: "Guernsey", start_date: nil, end_date: nil)
    Location.create!(code: "HM", name: "Heard Island and McDonald Islands", start_date: nil, end_date: nil)
    Location.create!(code: "HK", name: "Hong Kong", start_date: nil, end_date: nil)
    Location.create!(code: "UM-84", name: "Howland Island", start_date: nil, end_date: nil)
    Location.create!(code: "IM", name: "Isle of Man", start_date: nil, end_date: nil)
    Location.create!(code: "UM-86", name: "Jarvis Island", start_date: nil, end_date: nil)
    Location.create!(code: "JE", name: "Jersey", start_date: nil, end_date: nil)
    Location.create!(code: "UM-67", name: "Johnston Atoll", start_date: nil, end_date: nil)
    Location.create!(code: "UM-89", name: "Kingman Reef", start_date: nil, end_date: nil)
    Location.create!(code: "MO", name: "Macao", start_date: nil, end_date: nil)
    Location.create!(code: "MQ", name: "Martinique", start_date: nil, end_date: nil)
    Location.create!(code: "YT", name: "Mayotte", start_date: nil, end_date: nil)
    Location.create!(code: "ES-ML", name: "Melilla", start_date: nil, end_date: nil)
    Location.create!(code: "UM-71", name: "Midway Islands", start_date: nil, end_date: nil)
    Location.create!(code: "MS", name: "Montserrat", start_date: nil, end_date: nil)
    Location.create!(code: "UM-76", name: "Navassa Island", start_date: nil, end_date: nil)
    Location.create!(code: "NC", name: "New Caledonia", start_date: nil, end_date: nil)
    Location.create!(code: "NU", name: "Niue", start_date: nil, end_date: nil)
    Location.create!(code: "NF", name: "Norfolk Island", start_date: nil, end_date: nil)
    Location.create!(code: "MP", name: "Northern Mariana Islands", start_date: nil, end_date: nil)
    Location.create!(code: "PS", name: "Occupied Palestinian Territories", start_date: nil, end_date: nil)
    Location.create!(code: "UM-95", name: "Palmyra Atoll", start_date: nil, end_date: nil)
    Location.create!(code: "PN", name: "Pitcairn, Henderson, Ducie and Oeno Islands", start_date: nil, end_date: nil)
    Location.create!(code: "PR", name: "Puerto Rico", start_date: nil, end_date: nil)
    Location.create!(code: "AE-RK", name: "Ras al-Khaimah", start_date: nil, end_date: nil)
    Location.create!(code: "RE", name: "Réunion", start_date: nil, end_date: nil)
    Location.create!(code: "BQ-SA", name: "Saba", start_date: nil, end_date: nil)
    Location.create!(code: "BL", name: "Saint Barthélemy", start_date: nil, end_date: nil)
    Location.create!(code: "SH-HL", name: "Saint Helena", start_date: nil, end_date: nil)
    Location.create!(code: "PM", name: "Saint Pierre and Miquelon", start_date: nil, end_date: nil)
    Location.create!(code: "MF", name: "Saint-Martin (French part)", start_date: nil, end_date: nil)
    Location.create!(code: "AE-SH", name: "Sharjah", start_date: nil, end_date: nil)
    Location.create!(code: "BQ-SE", name: "Sint Eustatius", start_date: nil, end_date: nil)
    Location.create!(code: "SX", name: "Sint Maarten (Dutch part)", start_date: nil, end_date: nil)
    Location.create!(code: "GS", name: "South Georgia and South Sandwich Islands", start_date: nil, end_date: nil)
    Location.create!(code: "SJ", name: "Svalbard and Jan Mayen", start_date: nil, end_date: nil)
    Location.create!(code: "TW", name: "Taiwan", start_date: nil, end_date: nil)
    Location.create!(code: "TK", name: "Tokelau", start_date: nil, end_date: nil)
    Location.create!(code: "SH-TA", name: "Tristan da Cunha", start_date: nil, end_date: nil)
    Location.create!(code: "TC", name: "Turks and Caicos Islands", start_date: nil, end_date: nil)
    Location.create!(code: "AE-UQ", name: "Umm al-Quwain", start_date: nil, end_date: nil)
    Location.create!(code: "VI", name: "United States Virgin Islands", start_date: nil, end_date: nil)
    Location.create!(code: "UM-79", name: "Wake Island", start_date: nil, end_date: nil)
    Location.create!(code: "WF", name: "Wallis and Futuna", start_date: nil, end_date: nil)
    Location.create!(code: "EH", name: "Western Sahara", start_date: nil, end_date: nil)
    Location.create!(code: "AX", name: "Åland Islands", start_date: nil, end_date: nil)
  end

  def down
    Location.delete_all
  end
end
